"""Reviewed asset-price identities, independent of contract quantity conversion.

Each official asset page names the crypto asset and links its exact futures market.
Admission also checks native catalog base/quote/settlement/perpetual fields.
Unreviewed definitions remain excluded; typeLabel and symbols are not proof.
"""

MEXC_REVIEWED_IDENTITIES: dict[str, dict[str, str]] = {
    "BTC_USDT": {
        "base_asset": "BTC",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Bitcoin",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/BTC",
        "futures_url": "https://www.mexc.com/futures/BTC_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Bitcoin Price Today: Live BTC to USD Price Chart &amp; Market Data",
    },
    "ETH_USDT": {
        "base_asset": "ETH",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Ethereum",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ETH",
        "futures_url": "https://www.mexc.com/futures/ETH_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Ethereum Price Today: Live ETH to USD Price Chart &amp; Market Data",
    },
    "SOL_USDT": {
        "base_asset": "SOL",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Solana",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/SOL",
        "futures_url": "https://www.mexc.com/futures/SOL_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Solana Price Today: Live SOL to USD Price Chart &amp; Market Data",
    },
    "XRP_USDT": {
        "base_asset": "XRP",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "XRP Ledger",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/XRP",
        "futures_url": "https://www.mexc.com/futures/XRP_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "XRP Price Today: Live XRP to USD Price Chart &amp; Market Data",
    },
    "DOGE_USDT": {
        "base_asset": "DOGE",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Dogecoin",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/DOGE",
        "futures_url": "https://www.mexc.com/futures/DOGE_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "DOGE Price Today: Live DOGE to USD Price Chart &amp; Market Data",
    },
    "LTC_USDT": {
        "base_asset": "LTC",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Litecoin",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/LTC",
        "futures_url": "https://www.mexc.com/futures/LTC_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Litecoin Price Today: Live LTC to USD Price Chart &amp; Market Data",
    },
    "BNB_USDT": {
        "base_asset": "BNB",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "BNB Chain",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/BNB",
        "futures_url": "https://www.mexc.com/futures/BNB_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Binance Coin Price Today: Live BNB to USD Price Chart &amp; Market Data",
    },
    "ADA_USDT": {
        "base_asset": "ADA",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Cardano",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ADA",
        "futures_url": "https://www.mexc.com/futures/ADA_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Cardano Price Today: Live ADA to USD Price Chart &amp; Market Data",
    },
    "AVAX_USDT": {
        "base_asset": "AVAX",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Avalanche",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/AVAX",
        "futures_url": "https://www.mexc.com/futures/AVAX_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Avalanche Price Today: Live AVAX to USD Price Chart &amp; Market Data",
    },
    "TRX_USDT": {
        "base_asset": "TRX",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Tron",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/TRX",
        "futures_url": "https://www.mexc.com/futures/TRX_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Tron Price Today: Live TRX to USD Price Chart &amp; Market Data",
    },
}
