"""Fixed reviewed MEXC 50-asset source bundle; apply only after the staged gate.

Native price identities do not qualify external references or contract quantities.
"""

MEXC_REVIEWED_IDENTITIES: dict[str, dict[str, str]] = {
    "BTC_USDT": {
        "base_asset": "BTC",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Bitcoin",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/BTC",
        "futures_url": "https://www.mexc.com/futures/BTC_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Bitcoin Price Today: Live BTC to USD Price Chart &amp; Market Data",
    },
    "ETH_USDT": {
        "base_asset": "ETH",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Ethereum",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ETH",
        "futures_url": "https://www.mexc.com/futures/ETH_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Ethereum Price Today: Live ETH to USD Price Chart &amp; Market Data",
    },
    "SOL_USDT": {
        "base_asset": "SOL",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Solana",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/SOL",
        "futures_url": "https://www.mexc.com/futures/SOL_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Solana Price Today: Live SOL to USD Price Chart &amp; Market Data",
    },
    "XRP_USDT": {
        "base_asset": "XRP",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "XRP Ledger",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/XRP",
        "futures_url": "https://www.mexc.com/futures/XRP_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "XRP Price Today: Live XRP to USD Price Chart &amp; Market Data",
    },
    "DOGE_USDT": {
        "base_asset": "DOGE",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Dogecoin",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/DOGE",
        "futures_url": "https://www.mexc.com/futures/DOGE_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "DOGE Price Today: Live DOGE to USD Price Chart &amp; Market Data",
    },
    "LTC_USDT": {
        "base_asset": "LTC",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Litecoin",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/LTC",
        "futures_url": "https://www.mexc.com/futures/LTC_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Litecoin Price Today: Live LTC to USD Price Chart &amp; Market Data",
    },
    "BNB_USDT": {
        "base_asset": "BNB",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "BNB Chain",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/BNB",
        "futures_url": "https://www.mexc.com/futures/BNB_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Binance Coin Price Today: Live BNB to USD Price Chart &amp; Market Data",
    },
    "ADA_USDT": {
        "base_asset": "ADA",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Cardano",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ADA",
        "futures_url": "https://www.mexc.com/futures/ADA_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Cardano Price Today: Live ADA to USD Price Chart &amp; Market Data",
    },
    "AVAX_USDT": {
        "base_asset": "AVAX",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Avalanche",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/AVAX",
        "futures_url": "https://www.mexc.com/futures/AVAX_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Avalanche Price Today: Live AVAX to USD Price Chart &amp; Market Data",
    },
    "TRX_USDT": {
        "base_asset": "TRX",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Tron",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/TRX",
        "futures_url": "https://www.mexc.com/futures/TRX_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-09T21:46:34.629558+00:00",
        "page_title": "Tron Price Today: Live TRX to USD Price Chart &amp; Market Data",
    },
    "ZEC_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ZEC",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Zcash",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ZEC",
        "futures_url": "https://www.mexc.com/futures/ZEC_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Zcash Price Today: Live ZEC to USD Price Chart & Market Data",
    },
    "NEAR_USDT": {
        "identity_scope": "native_only",
        "base_asset": "NEAR",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "NEAR Protocol",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/NEAR",
        "futures_url": "https://www.mexc.com/futures/NEAR_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "NEAR Price Today: Live NEAR to USD Price Chart & Market Data",
    },
    "QNT_USDT": {
        "identity_scope": "native_only",
        "base_asset": "QNT",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Quant",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/QNT",
        "futures_url": "https://www.mexc.com/futures/QNT_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Quant Price Today: Live QNT to USD Price Chart & Market Data",
    },
    "LINK_USDT": {
        "identity_scope": "native_only",
        "base_asset": "LINK",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Chainlink",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/LINK",
        "futures_url": "https://www.mexc.com/futures/LINK_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Chainlink Price Today: Live LINK to USD Price Chart & Market Data",
    },
    "SUI_USDT": {
        "identity_scope": "native_only",
        "base_asset": "SUI",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Sui",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/SUI",
        "futures_url": "https://www.mexc.com/futures/SUI_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "SUI Price Today: Live SUI to USD Price Chart & Market Data",
    },
    "PEPE_USDT": {
        "identity_scope": "native_only",
        "base_asset": "PEPE",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "PEPE",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/PEPE",
        "futures_url": "https://www.mexc.com/futures/PEPE_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Pepe Price Today: Live PEPE to USD Price Chart & Market Data",
    },
    "WLD_USDT": {
        "identity_scope": "native_only",
        "base_asset": "WLD",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Worldcoin",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/WLD",
        "futures_url": "https://www.mexc.com/futures/WLD_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Worldcoin Price Today: Live WLD to USD Price Chart & Market Data",
    },
    "TAO_USDT": {
        "identity_scope": "native_only",
        "base_asset": "TAO",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Bittensor",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/TAO",
        "futures_url": "https://www.mexc.com/futures/TAO_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Bittensor Price Today: Live TAO to USD Price Chart & Market Data",
    },
    "RLC_USDT": {
        "identity_scope": "native_only",
        "base_asset": "RLC",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "iExec RLC",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/RLC",
        "futures_url": "https://www.mexc.com/futures/RLC_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "iExec RLC Price Today: Live RLC to USD Price Chart & Market Data",
    },
    "HYPE_USDT": {
        "identity_scope": "native_only",
        "base_asset": "HYPE",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Hyperliquid",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/HYPE",
        "futures_url": "https://www.mexc.com/futures/HYPE_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Hyperliquid Price Today: Live HYPE to USD Price Chart & Market Data",
    },
    "ENA_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ENA",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Ethena",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ENA",
        "futures_url": "https://www.mexc.com/futures/ENA_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Ethena Price Today: Live ENA to USD Price Chart & Market Data",
    },
    "ONDO_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ONDO",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Ondo",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ONDO",
        "futures_url": "https://www.mexc.com/futures/ONDO_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Ondo Price Today: Live ONDO to USD Price Chart & Market Data",
    },
    "ARB_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ARB",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Arbitrum",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ARB",
        "futures_url": "https://www.mexc.com/futures/ARB_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Arbitrum Price Today: Live ARB to USD Price Chart & Market Data",
    },
    "DOT_USDT": {
        "identity_scope": "native_only",
        "base_asset": "DOT",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Polkadot",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/DOT",
        "futures_url": "https://www.mexc.com/futures/DOT_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Polkadot Price Today: Live DOT to USD Price Chart & Market Data",
    },
    "TIA_USDT": {
        "identity_scope": "native_only",
        "base_asset": "TIA",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "TIA",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/TIA",
        "futures_url": "https://www.mexc.com/futures/TIA_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "TIA Price Today: Live TIA to USD Price Chart & Market Data",
    },
    "ATOM_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ATOM",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Cosmos",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ATOM",
        "futures_url": "https://www.mexc.com/futures/ATOM_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "COSMOS Price Today: Live ATOM to USD Price Chart & Market Data",
    },
    "AAVE_USDT": {
        "identity_scope": "native_only",
        "base_asset": "AAVE",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "AAVE",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/AAVE",
        "futures_url": "https://www.mexc.com/futures/AAVE_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "AaveToken Price Today: Live AAVE to USD Price Chart & Market Data",
    },
    "JUP_USDT": {
        "identity_scope": "native_only",
        "base_asset": "JUP",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Jupiter",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/JUP",
        "futures_url": "https://www.mexc.com/futures/JUP_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Jupiter Price Today: Live JUP to USD Price Chart & Market Data",
    },
    "APT_USDT": {
        "identity_scope": "native_only",
        "base_asset": "APT",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Aptos",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/APT",
        "futures_url": "https://www.mexc.com/futures/APT_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Aptos Price Today: Live APT to USD Price Chart & Market Data",
    },
    "INJ_USDT": {
        "identity_scope": "native_only",
        "base_asset": "INJ",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Injective",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/INJ",
        "futures_url": "https://www.mexc.com/futures/INJ_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Injective Price Today: Live INJ to USD Price Chart & Market Data",
    },
    "UNI_USDT": {
        "identity_scope": "native_only",
        "base_asset": "UNI",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Uniswap",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/UNI",
        "futures_url": "https://www.mexc.com/futures/UNI_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "UNISWAP Price Today: Live UNI to USD Price Chart & Market Data",
    },
    "ZRO_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ZRO",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "LayerZero",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ZRO",
        "futures_url": "https://www.mexc.com/futures/ZRO_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "LayerZero Price Today: Live ZRO to USD Price Chart & Market Data",
    },
    "DASH_USDT": {
        "identity_scope": "native_only",
        "base_asset": "DASH",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "DASH",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/DASH",
        "futures_url": "https://www.mexc.com/futures/DASH_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "DASH Price Today: Live DASH to USD Price Chart & Market Data",
    },
    "BAT_USDT": {
        "identity_scope": "native_only",
        "base_asset": "BAT",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Basic Attention Token",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/BAT",
        "futures_url": "https://www.mexc.com/futures/BAT_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "BAT Price Today: Live BAT to USD Price Chart & Market Data",
    },
    "HBAR_USDT": {
        "identity_scope": "native_only",
        "base_asset": "HBAR",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Hedera",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/HBAR",
        "futures_url": "https://www.mexc.com/futures/HBAR_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Hedera Price Today: Live HBAR to USD Price Chart & Market Data",
    },
    "SAND_USDT": {
        "identity_scope": "native_only",
        "base_asset": "SAND",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Sandbox",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/SAND",
        "futures_url": "https://www.mexc.com/futures/SAND_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Sandbox Price Today: Live SAND to USD Price Chart & Market Data",
    },
    "KAIA_USDT": {
        "identity_scope": "native_only",
        "base_asset": "KAIA",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Kaia",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/KAIA",
        "futures_url": "https://www.mexc.com/futures/KAIA_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Kaia Price Today: Live KAIA to USD Price Chart & Market Data",
    },
    "SEI_USDT": {
        "identity_scope": "native_only",
        "base_asset": "SEI",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "SEI",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/SEI",
        "futures_url": "https://www.mexc.com/futures/SEI_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "SEI Price Today: Live SEI to USD Price Chart & Market Data",
    },
    "FET_USDT": {
        "identity_scope": "native_only",
        "base_asset": "FET",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Fetch",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/FET",
        "futures_url": "https://www.mexc.com/futures/FET_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "FET Price Today: Live FET to USD Price Chart & Market Data",
    },
    "US_USDT": {
        "identity_scope": "native_only",
        "base_asset": "US",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Talus",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/US",
        "futures_url": "https://www.mexc.com/futures/US_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Talus Price Today: Live US to USD Price Chart & Market Data",
    },
    "FARTCOIN_USDT": {
        "identity_scope": "native_only",
        "base_asset": "FARTCOIN",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "FARTCOIN",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/FARTCOIN",
        "futures_url": "https://www.mexc.com/futures/FARTCOIN_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "FARTCOIN Price Today: Live FARTCOIN to USD Price Chart & Market Data",
    },
    "ICP_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ICP",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Internet Computer",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ICP",
        "futures_url": "https://www.mexc.com/futures/ICP_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Internet Computer Price Today: Live ICP to USD Price Chart & Market Data",
    },
    "ASTER_USDT": {
        "identity_scope": "native_only",
        "base_asset": "ASTER",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Aster",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/ASTER",
        "futures_url": "https://www.mexc.com/futures/ASTER_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Aster Price Today: Live ASTER to USD Price Chart & Market Data",
    },
    "MAGIC_USDT": {
        "identity_scope": "native_only",
        "base_asset": "MAGIC",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "MAGIC Token",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/MAGIC",
        "futures_url": "https://www.mexc.com/futures/MAGIC_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "MAGIC Price Today: Live MAGIC to USD Price Chart & Market Data",
    },
    "OP_USDT": {
        "identity_scope": "native_only",
        "base_asset": "OP",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "OP",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/OP",
        "futures_url": "https://www.mexc.com/futures/OP_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "OP Price Today: Live OP to USD Price Chart & Market Data",
    },
    "PYTH_USDT": {
        "identity_scope": "native_only",
        "base_asset": "PYTH",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Pyth Network",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/PYTH",
        "futures_url": "https://www.mexc.com/futures/PYTH_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Pyth Network Price Today: Live PYTH to USD Price Chart & Market Data",
    },
    "XLM_USDT": {
        "identity_scope": "native_only",
        "base_asset": "XLM",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Stellar",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/XLM",
        "futures_url": "https://www.mexc.com/futures/XLM_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Stellar Price Today: Live XLM to USD Price Chart & Market Data",
    },
    "BTW_USDT": {
        "identity_scope": "native_only",
        "base_asset": "BTW",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Bitway",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/BTW",
        "futures_url": "https://www.mexc.com/futures/BTW_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Bitway Price Today: Live BTW to USD Price Chart & Market Data",
    },
    "SHIB_USDT": {
        "identity_scope": "native_only",
        "base_asset": "SHIB",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Shiba Inu",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/SHIB",
        "futures_url": "https://www.mexc.com/futures/SHIB_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "SHIBAINU Price Today: Live SHIB to USD Price Chart & Market Data",
    },
    "PENGU_USDT": {
        "identity_scope": "native_only",
        "base_asset": "PENGU",
        "quote_asset": "USDT",
        "settle_asset": "USDT",
        "asset_class": "crypto",
        "project": "Pudgy Penguins",
        "price_unit": "quote_per_base",
        "identity_price_multiplier": "1",
        "classification_url": "https://www.mexc.com/price/PENGU",
        "futures_url": "https://www.mexc.com/futures/PENGU_USDT",
        "documentation_url": "https://www.mexc.com/api-docs/futures/market-endpoints/get-contract-info",
        "catalog_url": "https://api.mexc.com/api/v1/contract/detail/country",
        "reviewed_at": "2026-10-10T01:41:39.711475+00:00",
        "page_title": "Pudgy Penguins Price Today: Live PENGU to USD Price Chart & Market Data",
    },
}
